version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      -8080:80
    depends_on:
      - app
    volumes:

  app:
    build: ./web
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    
    environment:
      MYSQLROOT_PASSWORD: root 
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD: